name: Build natmap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout natmap
        uses: actions/checkout@v4
        with:
          repository: heiher/natmap
          ref: main

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git

      - name: Build
        run: |
          cmake -B build
          cmake --build build -j$(nproc)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: natmap
          path: build/natmap
